require("settings")
require("key_mappings")

require("plugins.plugins")
require("plugins.null-ls")
require("plugins.mason")
require("plugins.treesitter")
require("plugins.neodev")
require("plugins.dap")
require("plugins.doge")

require("servers")
require("auto_groups")
require("theme")

require("plugins.neotest")
require("plugins.chad-tree")
require("plugins.telescope")
require("plugins.project_nvim")
require("plugins.fidget")
require("plugins.lualine")
require("plugins.neovide")
require("plugins.autopairs")
