require("plugins.packer")
require("plugins.mason")
require("plugins.treesitter")
require("plugins.neotest")
require("plugins.dap")
require("plugins.doge")

require("servers")
require("settings")
require("key_mappings")
require("auto_groups")
require("theme")

-- Plugins
require("plugins.chad-tree")
require("plugins.telescope")
require("plugins.null-ls")
require("plugins.project_nvim")
require("plugins.fidget")
require("plugins.lualine")
require("plugins.neovide")
