#!/usr/bin/bash

source "src/essentials.sh"
source "src/zsh.sh"
source "src/omz.sh"
source "src/powerlevel10k.sh"
source "src/pyenv.sh"
source "src/nvm.sh"
source "src/nvim.sh"
source "src/tmux.sh"
source "src/rust.sh"
source "src/fdfind.sh"
source "src/fzf.sh"
source "src/go.sh"
source "src/aws.sh"
source "src/maven.sh"
source "src/ripgrep.sh"
