#!/usr/bin/env zsh

initdocker() {
  docker_init_file="$HOME/personal/dotfiles/docker/init.sh"
  if [[ -e $docker_init_file ]]
  then
   $docker_init_file
  else
    echo "DOCKER INIT FILE NOT FOUND!"
    exit 1
  fi
}
