#!/usr/bin/env zsh

queryinstallpackage() {
  # Query if package exists.
  local query=`dpkg-query -W -f='${Status}' "$1" 2>&1 | grep -c "ok installed"`
  echo "query is $query"

  if [[ "$query" -eq 0 ]] 
  then
    if [[ ! -z "$3" ]] 
    then
      sudo add-apt-repository "$3"
    fi

    if [[ "${2:-0}" -eq 0 ]]
    then
      sudo apt install "$1"
    else 
      sudo apt-get install "$1"
    fi
  fi
}
